<?php
$_lang['mxbackup'] = 'mxBackup';
$_lang['mxbackup_menu_desc'] = 'Production and anonymized development backups';
$_lang['mxbackup_intro'] = 'Run large backups from CLI/cron. Web runs are constrained by PHP and proxy timeouts.';
$_lang['mxbackup_profiles'] = 'Profiles'; $_lang['mxbackup_rules'] = 'Rules'; $_lang['mxbackup_history'] = 'History';
$_lang['mxbackup_tables'] = 'Database tables'; $_lang['mxbackup_masking'] = 'Anonymization';
$_lang['mxbackup_settings'] = 'Settings'; $_lang['mxbackup_settings_saved'] = 'Settings saved.';
$_lang['mxbackup_prod_backup'] = 'Create prod backup'; $_lang['mxbackup_dev_backup'] = 'Create dev backup'; $_lang['mxbackup_dev_dryrun'] = 'Dev dry-run';
$_lang['mxbackup_run_profile']='Profile'; $_lang['mxbackup_create_backup']='Create backup'; $_lang['mxbackup_dryrun']='Inspect contents';
$_lang['mxbackup_run'] = 'Run mxBackup'; $_lang['mxbackup_running'] = 'Creating backup…'; $_lang['mxbackup_finished'] = 'Operation completed.';
$_lang['mxbackup_confirm_run'] = 'Start backup?'; $_lang['mxbackup_confirm_dryrun'] = 'Inspect contents without creating an archive?'; $_lang['mxbackup_error'] = 'mxBackup error';
$_lang['mxbackup_name']='Name'; $_lang['mxbackup_description']='Description'; $_lang['mxbackup_mode']='Mode'; $_lang['mxbackup_active']='Active';
$_lang['mxbackup_mode_prod']='Production'; $_lang['mxbackup_mode_dev']='Development'; $_lang['mxbackup_mode_custom']='Custom'; $_lang['mxbackup_format']='Archive format';
$_lang['mxbackup_profile']='Profile'; $_lang['mxbackup_profile_id']='Profile ID'; $_lang['mxbackup_target_type']='Target type'; $_lang['mxbackup_target']='Target';
$_lang['mxbackup_action']='Action'; $_lang['mxbackup_value']='Value'; $_lang['mxbackup_priority']='Priority'; $_lang['mxbackup_status']='Status';
$_lang['mxbackup_archive']='Archive'; $_lang['mxbackup_size']='Size'; $_lang['mxbackup_started']='Started';
$_lang['mxbackup_completed']='Completed'; $_lang['mxbackup_duration']='Duration'; $_lang['mxbackup_seconds_short']='s';
$_lang['mxbackup_refresh']='Refresh'; $_lang['mxbackup_run_details']='Run details'; $_lang['mxbackup_run_type']='Run type';
$_lang['mxbackup_run_type_dry']='Composition check'; $_lang['mxbackup_run_type_backup']='Archive creation'; $_lang['mxbackup_no_archive_dry']='No archive is created';
$_lang['mxbackup_status_running']='Running'; $_lang['mxbackup_status_success']='Success'; $_lang['mxbackup_status_warning']='Completed with warnings'; $_lang['mxbackup_status_error']='Error';
$_lang['mxbackup_warnings']='Warnings'; $_lang['mxbackup_errors']='Errors'; $_lang['mxbackup_none']='None';
$_lang['mxbackup_search_table']='Search any part of the table name';
$_lang['mxbackup_files']='Site files'; $_lang['mxbackup_file_include']='Include'; $_lang['mxbackup_file_include_desc']='One path or pattern per line. * includes all files.'; $_lang['mxbackup_file_exclude']='Exclude'; $_lang['mxbackup_file_exclude_desc']='One path or pattern per line. End directories with /.';
$_lang['mxbackup_standard_masking']='Standard anonymization'; $_lang['mxbackup_standard_masking_short']='Standard rules'; $_lang['mxbackup_standard_masking_desc']='Required for development profiles. Protects MODX, miniShop2 and common personal fields.';
$_lang['mxbackup_table']='Table'; $_lang['mxbackup_column']='Column'; $_lang['mxbackup_sql_type']='SQL type'; $_lang['mxbackup_rows']='Rows'; $_lang['mxbackup_engine']='Engine'; $_lang['mxbackup_in_archive']='In archive'; $_lang['mxbackup_included']='Included'; $_lang['mxbackup_excluded']='Excluded';
$_lang['mxbackup_selection_mode']='New tables'; $_lang['mxbackup_table_mode_all_except']='Include automatically'; $_lang['mxbackup_table_mode_selected']='Selected only'; $_lang['mxbackup_include_all']='Include all'; $_lang['mxbackup_exclude_all']='Exclude all';
$_lang['mxbackup_masking_action']='Action'; $_lang['mxbackup_rule_source']='Rule source'; $_lang['mxbackup_source_standard']='Built in'; $_lang['mxbackup_source_custom']='Custom'; $_lang['mxbackup_source_none']='No rule'; $_lang['mxbackup_action_none']='Unchanged'; $_lang['mxbackup_action_mask']='Replace with test data'; $_lang['mxbackup_action_hide']='Clear value'; $_lang['mxbackup_action_hash']='SHA-256 hash'; $_lang['mxbackup_action_replace']='Fixed value'; $_lang['mxbackup_action_truncate']='Empty table';
$_lang['mxbackup_whole_table']='Whole table'; $_lang['mxbackup_select_table']='Select a profile and table.'; $_lang['mxbackup_truncate_table']='Empty table in dev copy'; $_lang['mxbackup_json_path']='JSON path'; $_lang['mxbackup_json_path_desc']='Optional, e.g. payment.token or items.*.email.'; $_lang['mxbackup_replacement']='Replacement'; $_lang['mxbackup_replacement_desc']='Used only by the Fixed value action.';
$_lang['mxbackup_standard_truncate_exists']='This table is already emptied by a built-in safety rule.'; $_lang['mxbackup_custom_truncate_exists']='A custom truncate rule already exists for this table.'; $_lang['mxbackup_confirm_truncate']='Remove all rows from this table in the development copy? The schema is preserved.'; $_lang['mxbackup_confirm_remove_rule']='Remove this custom rule? A built-in rule will take effect again when available.';
$_lang['mxbackup_report_files']='files'; $_lang['mxbackup_report_tables']='tables'; $_lang['mxbackup_report_masked_columns']='masked columns'; $_lang['mxbackup_report_truncated']='emptied tables'; $_lang['mxbackup_report_table_list']='Tables in archive'; $_lang['mxbackup_report_truncated_list']='Tables to empty';
$_lang['mxbackup_add_profile']='Add profile'; $_lang['mxbackup_edit_profile']='Edit profile'; $_lang['mxbackup_add_rule']='Add rule'; $_lang['mxbackup_edit_rule']='Edit rule';
$_lang['mxbackup_invalid_name']='Use letters, digits, _ and - only.'; $_lang['mxbackup_name_exists']='A profile with this name already exists.';
$_lang['mxbackup_invalid_json']='Invalid JSON.'; $_lang['mxbackup_builtin_profile_remove']='Built-in prod and dev profiles cannot be removed.'; $_lang['mxbackup_builtin_profile_rename']='Built-in prod and dev profiles cannot be renamed.'; $_lang['mxbackup_rule_not_found']='Rule not found.';
$_lang['mxbackup_profile_not_found']='Profile not found.'; $_lang['mxbackup_invalid_target_type']='Invalid target type.'; $_lang['mxbackup_invalid_action']='Invalid action.';
$_lang['mxbackup_rule_exists']='A custom rule already exists for this target.'; $_lang['mxbackup_invalid_column_target']='Column target must be table.column.'; $_lang['mxbackup_invalid_json_target']='JSON target must be table.column.path.'; $_lang['mxbackup_tables_load_error']='Could not load database tables.'; $_lang['mxbackup_table_not_found']='Table not found.'; $_lang['mxbackup_invalid_table_selection']='Invalid selected table list.'; $_lang['mxbackup_profile_save_error']='Could not save profile.'; $_lang['mxbackup_tables_saved']='Table selection saved.';
$_lang['mxbackup_config_valid']='Configuration is valid.';

$_lang['area_mxbackup_general'] = 'General';
$_lang['area_mxbackup_mail'] = 'Email';
$_lang['area_mxbackup_retention'] = 'Retention';
$_lang['setting_mxbackup.storage_path'] = 'Archive directory';
$_lang['setting_mxbackup.storage_path_desc'] = 'Absolute path outside the web root. Leave empty to use the backups directory next to the site root.';
$_lang['setting_mxbackup.config_dir'] = 'Profile configuration directory';
$_lang['setting_mxbackup.config_dir_desc'] = 'Directory containing PHP profile files managed by mxBackup. The {core_path} placeholder is supported; the default is core/config/mxbackup/profiles/.';
$_lang['setting_mxbackup.config_path'] = 'Global additional settings file';
$_lang['setting_mxbackup.config_path_desc'] = 'Optional PHP file overriding manager settings and profile files. When empty, mxBackup checks core/config/mxbackup.php.';
$_lang['setting_mxbackup.default_profile'] = 'Default profile';
$_lang['setting_mxbackup.default_profile_desc'] = 'Usually prod or dev.';
$_lang['setting_mxbackup.archive_format'] = 'Archive format';
$_lang['setting_mxbackup.archive_format_desc'] = 'tar.gz or zip.';
$_lang['setting_mxbackup.mail_enabled'] = 'Send email';
$_lang['setting_mxbackup.mail_enabled_desc'] = 'Disabled by default because production archives can contain sensitive data.';
$_lang['setting_mxbackup.mail_to'] = 'Recipients';
$_lang['setting_mxbackup.mail_to_desc'] = 'Comma-separated email addresses.';
$_lang['setting_mxbackup.mail_max_attachment_mb'] = 'Attachment limit, MB';
$_lang['setting_mxbackup.mail_max_attachment_mb_desc'] = 'Larger archives remain local; the email contains the report only.';
$_lang['setting_mxbackup.retention_days'] = 'Keep for days';
$_lang['setting_mxbackup.retention_days_desc'] = '0 disables the age limit.';
$_lang['setting_mxbackup.retention_count'] = 'Keep archives';
$_lang['setting_mxbackup.retention_count_desc'] = '0 disables the archive count limit.';
$_lang['setting_mxbackup.lock_ttl_minutes'] = 'Lock TTL, minutes';
$_lang['setting_mxbackup.lock_ttl_minutes_desc'] = 'Reference interval used to diagnose a stuck backup run.';
